import { readFile } from 'node:fs/promises';
import { gunzipSync } from 'node:zlib';
import { expect, test, type Locator, type Page } from '@playwright/test';
import type { CampaignRecord, DayCloseRecord, DocumentRecord, ExportArtifact, KnowledgeEntry, QcRecord, ShiftRecord, StockLot } from '../../shared/platform-contracts';
import { fixture, login } from './fixtures';

function form(page: Page, title: string) { return page.locator('.xp-form-panel').filter({ has: page.getByRole('heading', { name: title, exact: true }) }); }
async function submit<T>(page: Page, target: Locator, button: string, path: string): Promise<T> {
  const received = page.waitForResponse(response => new URL(response.url()).pathname === `/api/platform${path}` && response.request().method() === 'POST');
  await target.getByRole('button', { name: button, exact: true }).click();
  const response = await received, result = await response.json();
  expect(response.ok(), `${path}: ${result.code ?? 'request failed'}`).toBe(true);
  expect(result.ok).toBe(true);
  return result.data as T;
}
async function upload(page: Page, entityId: string, name: string, content: string) {
  const session = await (await page.request.get('/api/platform/session')).json();
  const response = await page.request.post('/api/platform/evidence/upload', { headers: { Origin: fixture().origin, 'X-CSRF-Token': session.data.csrfToken }, multipart: { entityId, file: { name, mimeType: 'text/plain', buffer: Buffer.from(content) } } });
  const result = await response.json();
  expect(response.ok(), `Actual file upload: ${result.code ?? 'request failed'}`).toBe(true);
  expect(result.data.kind).toBe('file');
  expect(result.data.size).toBe(Buffer.byteLength(content));
  return result.data as { id: string; sha256: string };
}
function localInput(stamp: Date) { return new Date(stamp.getTime() + 8 * 3600_000).toISOString().slice(0, 16); }
/** Inspect the downloaded archive bytes rather than accepting a successful export request alone. */
function tarContents(input: Buffer): Map<string, Buffer> {
  const bytes = input[0] === 0x1f && input[1] === 0x8b ? gunzipSync(input) : input;
  const result = new Map<string, Buffer>();
  for (let offset = 0; offset + 512 <= bytes.length; ) {
    const header = bytes.subarray(offset, offset + 512);
    if (header.every(byte => byte === 0)) break;
    const name = header.subarray(0, 100).toString('utf8').replace(/\0.*$/, '');
    const size = Number.parseInt(header.subarray(124, 136).toString('ascii').replace(/\0/g, '').trim(), 8);
    expect(Number.isSafeInteger(size) && size >= 0, 'Valid archive member size').toBe(true);
    expect(offset + 512 + size <= bytes.length, 'Complete archive member bytes').toBe(true);
    expect(result.has(name), 'No duplicate archive member can shadow approved bytes').toBe(false);
    result.set(name, bytes.subarray(offset + 512, offset + 512 + size));
    offset += 512 + Math.ceil(size / 512) * 512;
  }
  return result;
}

test('founder marketing UI stores rights, approves exact revision and downloads real manual caption and asset bundle', async ({ page }) => {
  test.setTimeout(90_000);
  await login(page, 'founder');
  await page.goto('/founder/marketing');
  const title = `QA marketing ${crypto.randomUUID()}`, caption = `Isolated QA caption ${title}. No product, pricing or sales claim.`;
  await page.getByRole('button', { name: 'Kempen baharu', exact: true }).click();
  const draftForm = form(page, 'Campaign draft');
  await draftForm.getByLabel('Nama kempen').fill(title);
  await draftForm.getByLabel('Objektif kempen').fill('Isolated first-party release journey verification');
  await draftForm.getByLabel('Caption / approved claims draft').fill(caption);
  const draft = await submit<CampaignRecord>(page, draftForm, 'Simpan draft revision', '/campaigns');
  expect(draft.status).toBe('draft');
  const assetText = `QA-authored owned file for ${title}. Test artifact only; no customer or business claims.`;
  const evidence = await upload(page, draft.id, 'qa-owned-asset.txt', assetText);
  const card = page.locator('.xp-campaign').filter({ has: page.getByRole('heading', { name: title, exact: true }) });
  await card.getByRole('button', { name: 'Edit revision', exact: true }).click();
  const editor = form(page, `Edit ${title}`);
  await editor.getByLabel('Aset: ID').fill(`qa-owned|QA authored text|Owned test artifact generated by this QA test|No person depicted or personal data|${evidence.id}`);
  const edited = await submit<CampaignRecord>(page, editor, 'Simpan draft revision', `/campaigns/${draft.id}/update`);
  expect(edited.assets[0].evidenceId).toBe(evidence.id);
  await card.locator('summary').filter({ hasText: 'Assets & rights' }).click();
  await expect(card).toContainText('Owned test artifact');
  await card.getByRole('button', { name: 'Review & approve', exact: true }).click();
  const approvalForm = form(page, `Approve exact revision ${edited.revision}`);
  await approvalForm.getByLabel('Approval expiry (MYT)').fill(localInput(new Date(Date.now() + 3600_000)));
  const approved = await submit<CampaignRecord>(page, approvalForm, 'Sahkan copy, assets & revision', `/campaigns/${draft.id}/approve`);
  expect(approved.copy).toBe(caption);
  expect(approved.revision).toBe(edited.revision + 1);
  await expect(card.locator('.xp-status')).toHaveText('approved');
  const captionDownload = page.waitForEvent('download');
  const captionReceipt = page.waitForResponse(response => new URL(response.url()).pathname === `/api/platform/campaigns/${draft.id}/export` && response.request().method() === 'POST');
  await card.getByRole('button', { name: 'Export caption', exact: true }).click();
  const textDownload = await captionDownload;
  expect(await textDownload.failure()).toBeNull();
  expect(await readFile((await textDownload.path())!, 'utf8')).toBe(caption);
  const textArtifact = (await (await captionReceipt).json()).data as ExportArtifact;
  expect(textArtifact.status).toBe('exported');
  expect(textArtifact.campaignRevision).toBe(approved.revision);
  await expect(card.getByRole('button', { name: 'Download asset bundle', exact: true })).toBeEnabled();
  const bundleDownload = page.waitForEvent('download');
  const bundleReceipt = page.waitForResponse(response => new URL(response.url()).pathname === `/api/platform/campaigns/${draft.id}/export` && response.request().method() === 'POST');
  await card.getByRole('button', { name: 'Download asset bundle', exact: true }).click();
  const downloaded = await bundleDownload;
  expect(await downloaded.failure()).toBeNull();
  const entries = tarContents(await readFile((await downloaded.path())!));
  expect([...entries.keys()].sort()).toEqual(['caption.txt', `${evidence.id}.txt`].sort());
  expect(entries.get('caption.txt')?.toString('utf8')).toBe(caption);
  expect(entries.get(`${evidence.id}.txt`)?.toString('utf8')).toBe(assetText);
  const bundleArtifact = (await (await bundleReceipt).json()).data as ExportArtifact;
  expect(bundleArtifact.fileRefs).toEqual([evidence.id]);
  expect(bundleArtifact.status).toBe('exported');
  expect(bundleArtifact.campaignRevision).toBe(approved.revision);
  await page.reload();
  await expect(card).toContainText(caption);
  await expect(card.locator('.xp-status')).toHaveText('approved');
  await expect(page.getByText('Tiada akaun social connected yang disahkan', { exact: false }).first()).toBeVisible();
});

test('founder creates approved QA SOP and releases a quarantined QA batch with uploaded evidence through inspection UI', async ({ page }) => {
  test.setTimeout(90_000);
  await login(page, 'founder');
  const suffix = crypto.randomUUID(), title = `QA measurement source ${suffix}`, batchId = `QA-BATCH-${suffix}`, outletId = `qa-qc-${suffix}`;
  await page.goto('/founder/documents');
  await page.getByRole('button', { name: 'Dokumen baharu', exact: true }).click();
  const sourceForm = form(page, 'Dokumen baharu');
  await sourceForm.getByLabel('Tajuk').fill(title);
  await sourceForm.getByLabel('Kandungan Markdown').fill('# Isolated QA measurement policy\n\nQA fixture only, not a product or food-safety policy.\nMeasurement qa_unit_count uses unit; test acceptance range 1 through 3.');
  await sourceForm.getByLabel('Visibility').selectOption('business');
  const document = await submit<DocumentRecord>(page, sourceForm, 'Simpan rekod', '/documents');
  await page.goto('/founder/knowledge');
  await page.getByRole('button', { name: 'Publish knowledge', exact: true }).click();
  const publishForm = form(page, 'Publish document sebagai SOP / knowledge');
  await publishForm.getByLabel('Source document').selectOption(document.id);
  const knowledge = await submit<KnowledgeEntry>(page, publishForm, 'Approve & publish exact version', `/documents/${document.id}/publish`);
  expect(knowledge.version).toBe(document.version);
  await page.goto('/founder/qc');
  await page.getByRole('button', { name: 'Define SOP readings', exact: true }).click();
  const policyForm = form(page, 'Sahkan measurement thresholds');
  await policyForm.getByLabel('Approved source knowledge').selectOption(knowledge.id);
  await policyForm.getByLabel('Verified thresholds').fill('qa_unit_count|unit|1|3');
  const policy = await submit<{ id: string; knowledgeId: string; knowledgeVersion: number }>(page, policyForm, 'Approve QC policy', '/qc/sops');
  expect(policy.knowledgeId).toBe(knowledge.id);
  expect(policy.knowledgeVersion).toBe(knowledge.version);
  const currentProducts = await (await page.request.get('/api/platform/catalogue?limit=1')).json();
  expect(currentProducts.data.length).toBeGreaterThan(0);
  const productId = currentProducts.data[0].id as string;
  await page.goto('/founder/inventory');
  await page.getByRole('button', { name: 'Receive stock', exact: true }).click();
  const receiveForm = form(page, 'Rekod penerimaan stok');
  const productSelect = receiveForm.getByLabel('Produk');
  await expect(productSelect).toBeVisible();
  const productsPanel = page.locator('.xp-panel').filter({ has: page.getByRole('heading', { name: 'Produk & harga', exact: true }) });
  // Published and admin listings have different ordering. Load real pages until this current product is selectable.
  for (let index = 0; await productSelect.locator(`option[value="${productId}"]`).count() === 0; index++) {
    expect(index, 'Current published product must appear in the paginated admin catalogue').toBeLessThan(10);
    const loadMore = productsPanel.getByRole('button', { name: 'Muat lagi rekod', exact: true });
    await expect(loadMore).toBeVisible();
    const previous = await productSelect.locator('option').count();
    await loadMore.click();
    await expect.poll(() => productSelect.locator('option').count()).toBeGreaterThan(previous);
  }
  await productSelect.selectOption(productId);
  await receiveForm.getByLabel('Outlet / lokasi').fill(outletId);
  await receiveForm.getByLabel('Kuantiti unit').fill('2');
  await receiveForm.getByLabel('Batch ID').fill(batchId);
  await receiveForm.getByLabel('Keadaan stok').selectOption('quarantine');
  await receiveForm.getByLabel('Sebab / receiving reference').fill('Isolated QA two-unit receiving fixture for release evidence, not production inventory.');
  const lot = await submit<StockLot>(page, receiveForm, 'Simpan rekod', '/inventory/receive');
  expect(lot.status).toBe('quarantine');
  const evidence = await upload(page, lot.id, 'qa-batch-measurement.txt', `QA batch ${batchId}: fixture qa_unit_count=2 unit; isolated test evidence only.`);
  await page.goto('/founder/qc');
  await page.getByRole('button', { name: 'Rekod inspection', exact: true }).click();
  const inspectionForm = form(page, 'Rekod QC inspection');
  await inspectionForm.getByLabel('Batch ID').fill(batchId);
  await inspectionForm.getByLabel('Outlet ID').fill(outletId);
  await inspectionForm.getByLabel('Approved SOP').selectOption(policy.id);
  await inspectionForm.getByLabel('Actual readings').fill('qa_unit_count|2|unit');
  await inspectionForm.getByLabel('Evidence IDs').fill(evidence.id);
  const inspection = await submit<QcRecord>(page, inspectionForm, 'Simpan QC untuk review', '/qc');
  expect(inspection.status).toBe('review');
  const card = page.locator('.xp-qc').filter({ has: page.getByRole('heading', { name: `Batch ${batchId}`, exact: true }) });
  await card.getByRole('button', { name: 'Review & release', exact: true }).click();
  const released = await submit<QcRecord>(page, card, 'Sahkan SOP, readings & release', `/qc/${inspection.id}/release`);
  expect(released.status).toBe('released');
  await expect(card.locator('.xp-status')).toHaveText('released');
  const inventory = await (await page.request.get('/api/platform/inventory')).json();
  expect(inventory.data.lots.find((record: StockLot) => record.id === lot.id).status).toBe('available');
  await page.reload();
  await expect(card).toContainText('1 evidence IDs');
  await expect(card.locator('.xp-status')).toHaveText('released');
});

test('founder shift handoff, acknowledgement and zero-cash QA day-close persist through real UI commands', async ({ page }) => {
  test.setTimeout(90_000);
  await login(page, 'founder');
  const outletId = `qa-shift-${crypto.randomUUID()}`, note = 'Isolated QA zero-unit outlet handoff, no unresolved work or production cash activity.';
  await page.goto('/founder/shifts');
  await page.getByRole('button', { name: 'Buka shift', exact: true }).click();
  const openingForm = form(page, 'Buka shift');
  await openingForm.getByLabel('Outlet ID').fill(outletId);
  await openingForm.getByLabel('Assigned staff IDs').fill(fixture().founder.userId);
  await openingForm.getByLabel('Opening unit count').fill('0');
  const shift = await submit<ShiftRecord>(page, openingForm, 'Simpan rekod', '/shifts');
  const card = page.locator('.xp-shift').filter({ has: page.getByRole('heading', { name: `Outlet ${outletId}`, exact: true }) });
  await card.getByRole('button', { name: 'Handoff shift', exact: true }).click();
  const handoffForm = form(page, 'Serahan shift');
  await handoffForm.getByLabel('Closing unit count').fill('0');
  await handoffForm.getByLabel('Handoff / unresolved issues').fill(note);
  const handoff = await submit<ShiftRecord>(page, handoffForm, 'Simpan handoff', `/shifts/${shift.id}/handoff`);
  expect(handoff.status).toBe('handoff');
  await card.getByRole('button', { name: 'Acknowledge', exact: true }).click();
  const closed = await submit<ShiftRecord>(page, card, 'Sahkan penerimaan custody', `/shifts/${shift.id}/acknowledge`);
  expect(closed.status).toBe('closed');
  expect(closed.acknowledgedBy).toBe(fixture().founder.userId);
  await page.reload();
  await expect(card).toContainText(note);
  await expect(card.locator('.xp-status')).toHaveText('closed');
  await page.goto('/founder/qc');
  await page.getByRole('button', { name: 'Rekod closing count', exact: true }).click();
  const countForm = form(page, 'Closing cash count'), day = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kuala_Lumpur', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
  await countForm.getByLabel('Outlet ID').fill(outletId);
  await countForm.getByLabel('Business date (MYT)').fill(day);
  await countForm.getByLabel('Counted cash (RM)').fill('0');
  const close = await submit<DayCloseRecord>(page, countForm, 'Simpan rekod', '/dayclose');
  expect(close.paymentRefs).toEqual([]);
  expect(close.expectedCashSen).toBe(0);
  expect(close.discrepancySen).toBe(0);
  const closeCard = page.locator('.xp-close').filter({ has: page.getByRole('heading', { name: `${day} · ${outletId}`, exact: true }) });
  const reviewForm = closeCard.locator('.xp-form-panel').filter({ has: page.getByRole('heading', { name: 'Review close', exact: true }) });
  await reviewForm.getByLabel('Review / variance resolution').fill('QA isolated outlet has no cash payment records; zero count verified for this fixture.');
  const approved = await submit<DayCloseRecord>(page, reviewForm, 'Approve close', `/dayclose/${close.id}/approve`);
  expect(approved.status).toBe('approved');
  await page.reload();
  await expect(closeCard.locator('.xp-status')).toHaveText('approved');
  await expect(closeCard).toContainText('no cash payment records');
});
