import type { AgentResult, Decision, JobRecord, WorkEstimate, UsageSnapshot } from '../../shared/platform-contracts';
import { Auth, type Principal } from '../platform/auth';
import { Commerce } from '../platform/commerce';
import { Work } from '../platform/work';
import { fields, fail, id, now, object, oneOf, PlatformStore, text, integer, strings } from '../platform/store';

export function admitWork(estimate:WorkEstimate,usage:UsageSnapshot):Decision {if(!usage.available||usage.observedUnits===null||usage.limitUnits===null)return {allowed:false,reasonCode:'USAGE_UNKNOWN'};if(estimate.providerId!==usage.providerId||!Number.isFinite(estimate.estimatedUnits)||estimate.estimatedUnits<0||usage.observedUnits<0||usage.limitUnits<0)return {allowed:false,reasonCode:'INVALID_ESTIMATE'};return usage.observedUnits+estimate.estimatedUnits<=usage.limitUnits?{allowed:true,reasonCode:'WITHIN_QUOTA'}:{allowed:false,reasonCode:'QUOTA_EXCEEDED'};}
export class Jobs {
  constructor(readonly store:PlatformStore,readonly auth:Auth,readonly commerce:Commerce,readonly work:Work){}
  usage():UsageSnapshot{const day=now().slice(0,10),limit=integer(Number(process.env.PLATFORM_LOCAL_JOB_DAILY_LIMIT??'100'),'Had pekerjaan lokal',1,10000);return {providerId:'local_first_party',observedUnits:this.store.all<JobRecord>('jobs').filter(j=>j.createdAt.slice(0,10)===day&&j.kind!=='research').length,limitUnits:limit,available:true,observedAt:now(),resetAt:new Date(Date.parse(day)+24*3600_000).toISOString()};}
  all(actor:Principal){if(!this.auth.has(actor,'founder')&&!this.auth.has(actor,'developer'))fail('FORBIDDEN',403);return this.store.all<JobRecord>('jobs').map(job=>this.auth.has(actor,'founder')?job:{id:job.id,kind:job.kind,status:job.status,attempt:job.attempt,reasonCode:job.reasonCode,createdAt:job.createdAt,leaseUntil:job.leaseUntil});}
  enqueue(actor:Principal,raw:unknown,key:unknown){this.auth.founder(actor);const input=object(raw);fields(input,['kind','entityId','skillVersion','scope']);const kind=oneOf(input.kind,['morning_brief','case_summary','research'] as const),entityId=text(input.entityId);if(kind==='case_summary'&&!this.store.get('cases',entityId)||kind==='morning_brief'&&entityId!=='business')fail('JOB_SOURCE_MISMATCH',400);if(entityId!=='business')this.work.entity(actor,entityId);return this.commerce.idem(actor,'job.enqueue',key,raw,()=>{if(kind!=='research'&&!admitWork({operation:'local_job',providerId:'local_first_party',estimatedUnits:1},this.usage()).allowed)fail('LOCAL_JOB_BUDGET_EXCEEDED',429);const record:JobRecord={id:id(),kind,entityId,skillVersion:text(input.skillVersion,'Versi skill',120),scope:text(input.scope,'Scope',120),ownerId:actor.user.id,status:kind==='research'?'blocked':'queued',attempt:0,idempotencyKey:text(key),createdAt:now(),...(kind==='research'?{reasonCode:'RESEARCH_ADAPTER_UNAVAILABLE'}:{})};this.store.save('jobs',record);this.store.audit(actor.user.id,'job.enqueue',record.id);return record;});}
  claimJob(workerId:string,leaseSeconds=30):JobRecord|null{return this.store.atomic(()=>{const controls=this.store.get<{workerAdmission:string;activeRelease:string}>('runtime_controls','runtime');if(controls?.workerAdmission==='paused'||controls?.activeRelease==='platform-local-readonly-v1')return null;integer(leaseSeconds,'Lease seconds',1,300);const jobs=this.store.all<JobRecord>('jobs');for(const job of jobs){if(job.status==='running'&&job.leaseUntil&&job.leaseUntil<=now()){this.store.save('jobs',{...job,status:job.attempt>=3?'failed' as const:'queued' as const,reasonCode:'LEASE_EXPIRED'});}}const candidate=this.store.all<JobRecord>('jobs').find(j=>j.status==='queued'&&j.attempt<3);if(!candidate)return null;const granted:JobRecord={...candidate,status:'running',attempt:candidate.attempt+1,leaseOwner:text(workerId),leaseUntil:new Date(Date.now()+leaseSeconds*1000).toISOString()};this.store.save('jobs',granted);return granted;});}
  completeJob(jobId:string,workerId:string,result:AgentResult):JobRecord{return this.store.atomic(()=>{const job=this.store.require<JobRecord>('jobs',jobId);if(job.status!=='running'||job.leaseOwner!==workerId||!job.leaseUntil||job.leaseUntil<=now())fail('LEASE_LOST',409);if(!['completed','partial','unknown','blocked'].includes(result.status)||!Array.isArray(result.artifactIds)||!Array.isArray(result.evidenceIds)||!Array.isArray(result.unknownReasons))fail('INVALID_AGENT_OUTPUT');strings(result.artifactIds,100);strings(result.evidenceIds,100);strings(result.unknownReasons,100);const updated:JobRecord={...job,status:result.status==='completed'?'completed':result.status==='blocked'?'blocked':'unknown',result,checkpoint:'LOCAL_RESULT_PERSISTED'};delete updated.leaseUntil;delete updated.leaseOwner;this.store.save('jobs',updated);return updated;});}
  executeLocal(jobId:string,workerId:string):JobRecord{return this.store.atomic(()=>{const job=this.store.require<JobRecord>('jobs',jobId);if(job.status!=='running'||job.leaseOwner!==workerId||!job.leaseUntil||job.leaseUntil<=now())fail('LEASE_LOST',409);const memberships=this.auth.memberships(job.ownerId);if(!memberships.some(m=>m.role==='founder'))return this.completeJob(jobId,workerId,{status:'blocked',artifactIds:[],evidenceIds:[],unknownReasons:['OWNER_GRANT_REVOKED']});if(job.kind==='case_summary'&&!this.store.get('cases',job.entityId)||job.kind==='morning_brief'&&job.entityId!=='business')return this.completeJob(jobId,workerId,{status:'blocked',artifactIds:[],evidenceIds:[],unknownReasons:['JOB_SOURCE_MISMATCH']});const artifactId=id();const content=job.kind==='morning_brief'?{orders:this.store.all('orders').length,openCases:this.store.all<{status:string}>('cases').filter(c=>c.status!=='resolved').length,openTasks:this.store.all<{status:string}>('tasks').filter(t=>t.status!=='done').length,generatedAt:now(),source:'local_authoritative'}:{caseId:job.entityId,case:this.store.get('cases',job.entityId),generatedAt:now(),source:'local_authoritative'};if(job.kind==='research')return this.completeJob(jobId,workerId,{status:'blocked',artifactIds:[],evidenceIds:[],unknownReasons:['RESEARCH_ADAPTER_UNAVAILABLE']});this.store.save('job_artifacts',{id:artifactId,jobId,ownerId:job.ownerId,content});return this.completeJob(jobId,workerId,{status:'completed',artifactIds:[artifactId],evidenceIds:[],unknownReasons:[]});});}
  cancel(actor:Principal,jobId:string){if(!this.auth.has(actor,'founder')&&!this.auth.has(actor,'developer'))fail('FORBIDDEN',403);const job=this.store.require<JobRecord>('jobs',jobId);if(['completed','cancelled'].includes(job.status))fail('INVALID_TRANSITION',409);const updated={...job,status:'cancelled' as const,reasonCode:'OPERATOR_CANCELLED'};delete updated.leaseOwner;delete updated.leaseUntil;this.store.save('jobs',updated);this.store.audit(actor.user.id,'job.cancel',jobId);return this.auth.has(actor,'founder')?updated:{id:updated.id,kind:updated.kind,status:updated.status,attempt:updated.attempt,reasonCode:updated.reasonCode,createdAt:updated.createdAt};}
}
