import { useEffect, useMemo, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { ArrowDownToLine, ArrowRight, ArrowUpRight, BarChart3, Check, ChevronRight, Clock3, Database, FileText, MapPin, Moon, Package, Search, ShieldCheck, Sparkles, Sun, Truck, X } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { appStore } from '@/services/store';
import type { OrderItem } from '@/services/store';
import { buildDashboard, cityLabel, filterOrders, money, statusColors, statusLabels } from './model';
import type { Period } from './model';
import './dashboard.css';

type ArtifactChart = { title?: string; data?: { label: string; value: number }[] };
type Artifact = { title?: string; kpis?: { label: string; value: string; trend?: string }[]; main_chart?: ArtifactChart; secondary_chart?: ArtifactChart; recent_activity?: { text: string }[] };
type Props = { theme: 'dark' | 'light'; onToggleTheme: () => void; onAction: (message?: string) => void; setActiveTab?: (tab: string) => void; dashboards?: Artifact[] };
type Detail = { title: string; description: string; orders: OrderItem[] };

function Panel({ children, className = '' }: { children: ReactNode; className?: string }) {
  return <section className={`dc-panel ${className}`}>{children}</section>;
}

function SavedArtifact({ dashboard }: { dashboard: Artifact }) {
  return <Panel><span className="dc-demo-label">ANALITIK CONTOH / HASIL EJEN · BELUM DISAHKAN</span><h2>{dashboard.title || 'Dashboard analitik'}</h2>
    <div className="dc-artifact-kpis">{dashboard.kpis?.map((kpi, index) => <div key={index}><span>{kpi.label}</span><strong>{kpi.value}</strong>{kpi.trend && <span>{kpi.trend}</span>}</div>)}</div>
    {[dashboard.main_chart, dashboard.secondary_chart].filter(Boolean).map((chart, index) => <div key={index}><h3 className="dc-artifact-heading">{chart?.title}</h3><div className="dc-artifact-data">{chart?.data?.map((item, itemIndex) => <span key={itemIndex}>{item.label}<strong>{Number.isFinite(item.value) ? item.value.toLocaleString() : 'Tidak tersedia'}</strong></span>)}</div></div>)}
    {dashboard.recent_activity?.length ? <div><h3 className="dc-artifact-heading">Catatan analitik</h3><ul className="dc-artifact-notes">{dashboard.recent_activity.map((activity, index) => <li key={index}>{activity.text}</li>)}</ul></div> : null}
  </Panel>;
}

function OrderRows({ orders, onSelect }: { orders: OrderItem[]; onSelect?: (order: OrderItem) => void }) {
  return <div className="dc-table-wrap"><table className="dc-table"><thead><tr><th>Pesanan / produk</th><th>Wilayah</th><th>Status</th><th>Nilai</th></tr></thead><tbody>
    {orders.map(order => <tr key={order.order_id}><td>{onSelect ? <button className="dc-order-link" onClick={() => onSelect(order)}>{order.order_id}<ArrowUpRight size={13} /></button> : <strong>{order.order_id}</strong>}<span className="dc-item-name">{order.items}</span></td><td>{cityLabel(order.city)}</td><td><span className={`dc-status dc-status-${order.status}`}>{statusLabels[order.status]}</span></td><td className="dc-number">{money(order.amount)}</td></tr>)}
  </tbody></table>{orders.length === 0 && <div className="dc-empty"><Package size={24} /><strong>Tiada pesanan untuk paparan ini</strong><span>Cuba wilayah atau tempoh yang lain.</span></div>}</div>;
}

export function DashboardView({ theme, onToggleTheme, onAction, setActiveTab, dashboards = [] }: Props) {
  const [orders, setOrders] = useState(() => appStore.getOrders());
  const [period, setPeriod] = useState<Period>('all');
  const [region, setRegion] = useState('all');
  const [query, setQuery] = useState('');
  const [tableTab, setTableTab] = useState<'all' | 'attention' | 'delivered'>('all');
  const [detail, setDetail] = useState<Detail | null>(null);
  const dark = theme === 'dark';
  const [notice, setNotice] = useState('');
  const dialogRef = useRef<HTMLDialogElement>(null);
  const originRef = useRef<HTMLElement | null>(null);
  useEffect(() => appStore.subscribe(() => setOrders(appStore.getOrders())), []);
  useEffect(() => {
    const dialog = dialogRef.current;
    if (detail && dialog && !dialog.open) { originRef.current = document.activeElement as HTMLElement; dialog.showModal(); }
    if (!detail && dialog?.open) dialog.close();
  }, [detail]);
  useEffect(() => { if (!notice) return; const timer = window.setTimeout(() => setNotice(''), 4000); return () => window.clearTimeout(timer); }, [notice]);
  const regions = useMemo(() => [...new Set(orders.map(order => order.city.trim().toLowerCase()))].sort(), [orders]);
  const filtered = useMemo(() => filterOrders(orders, period, region), [orders, period, region]);
  const model = useMemo(() => buildDashboard(filtered), [filtered]);
  const latestDate = orders.map(order => Date.parse(order.date)).filter(Number.isFinite).sort((a, b) => b - a)[0];
  const tableOrders = filtered.filter(order => (tableTab === 'all' || (tableTab === 'attention' ? ['Delayed', 'Processing'].includes(order.status) : order.status === 'Delivered'))
    && `${order.order_id} ${order.items} ${order.city}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => Date.parse(b.date) - Date.parse(a.date));
  const navigate = (tab: string) => setActiveTab?.(tab);
  const openOrders = (title: string, description: string, records = filtered) => setDetail({ title, description, orders: records });
  const closeDetail = () => { setDetail(null); };
  const exportCsv = () => {
    const escape = (value: string | number) => `"${String(value).replace(/^[=+@\-\t\r]/, "'$&").replace(/"/g, '""')}"`;
    const rows = [['Pesanan', 'Wilayah', 'Status', 'Nilai MYR', 'Tarikh'], ...filtered.map(order => [order.order_id, order.city, order.status, order.amount, order.date])];
    const url = URL.createObjectURL(new Blob(['\uFEFF' + rows.map(row => row.map(escape).join(',')).join('\r\n')], { type: 'text/csv;charset=utf-8;' }));
    const link = document.createElement('a'); link.href = url; link.download = 'abangcolek-pesanan.csv'; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000);
    setNotice(`${filtered.length} rekod dieksport mengikut filter aktif.`);
  };
  const leader = model.regions[0];
  const filtersActive = period !== 'all' || region !== 'all';
  const resetFilters = () => { setPeriod('all'); setRegion('all'); };
  const delayedCount = model.attention.filter(order => order.status === 'Delayed').length;
  return <div className="dc-dashboard" data-theme={dark ? 'dark' : 'light'}>
    <div className="dc-container">
      <header className="dc-header"><div><div className="dc-eyebrow"><span className="dc-brand-mark"><BarChart3 size={13} /></span> ABANGCOLEK / WORKSPACE</div><h1>Selamat datang kembali<span>.</span></h1><p>Ruang operasi anda. Semua keutamaan, dalam satu pandangan.</p></div><div className="dc-header-actions"><button className="dc-icon-button" aria-label={dark ? 'Tukar ke tema cerah' : 'Tukar ke tema gelap'} onClick={onToggleTheme}>{dark ? <Sun size={18} /> : <Moon size={18} />}</button><button className="dc-button dc-secondary" onClick={exportCsv}><ArrowDownToLine size={15} /> Eksport</button><button className="dc-button dc-primary" onClick={() => onAction('Analisis pesanan Abang Colek dan bina dashboard operasi berdasarkan rekod yang tersedia. Nyatakan sumber dan tempoh data.')}><Sparkles size={15} /> Analisis AI</button></div></header>
      <div className="dc-toolbar"><div className="dc-view-label"><span className="dc-view-dot" /> Ringkasan operasi <span className="dc-demo-label">REKOD TEMPATAN</span></div><div className="dc-filters">{filtersActive && <button className="dc-filter-reset" onClick={resetFilters}><X size={13} /> Reset filter</button>}<label><MapPin size={14} /><span className="sr-only">Filter wilayah</span><select aria-label="Filter wilayah" value={region} onChange={event => setRegion(event.target.value)}><option value="all">Semua wilayah</option>{regions.map(city => <option value={city} key={city}>{cityLabel(city)}</option>)}</select></label><label><Clock3 size={14} /><span className="sr-only">Filter tempoh</span><select aria-label="Filter tempoh" value={period} onChange={event => setPeriod(event.target.value as Period)}><option value="all">Semua rekod</option><option value="30">30 hari terakhir</option><option value="7">7 hari terakhir</option></select></label></div></div>
      <div className="dc-kpi-grid">
        {[{ label: 'Nilai pesanan', value: money(model.orderValue), caption: 'Tidak termasuk refund & batal', icon: BarChart3, explanation: 'Jumlah nilai pesanan Delivered, Processing dan Delayed. Ini bukan pengesahan wang diterima.', records: filtered.filter(order => !['Refunded', 'Cancelled'].includes(order.status)) },
          { label: 'Pesanan selesai', value: filtered.length ? `${Math.round(model.deliveryRate)}%` : '—', caption: `${model.delivered} daripada ${filtered.length} pesanan · ${delayedCount} tertunda`, icon: Truck, explanation: 'Peratus Delivered daripada semua pesanan dalam filter aktif. Semak rekod ini untuk bukti pesanan selesai.', records: filtered.filter(order => order.status === 'Delivered') },
          { label: 'Pesanan direkodkan', value: String(filtered.length).padStart(2, '0'), caption: `${model.delivered} pesanan selesai`, icon: Package, explanation: 'Semua pesanan yang memenuhi filter aktif.', records: filtered },
          { label: 'Purata nilai pesanan', value: money(model.averageOrder), caption: 'Daripada pesanan yang layak', icon: ArrowUpRight, explanation: 'Nilai pesanan dibahagi jumlah pesanan, tidak termasuk refund dan batal.', records: filtered.filter(order => !['Refunded', 'Cancelled'].includes(order.status)) },
          { label: 'Perlu perhatian', value: String(model.attention.length).padStart(2, '0'), caption: `${model.attention.filter(order => order.status === 'Delayed').length} tertunda · ${model.attention.filter(order => order.status === 'Processing').length} diproses`, icon: Clock3, explanation: 'Pesanan berstatus Delayed atau Processing, diutamakan mengikut status dan tarikh.', records: model.attention }].map((metric, index) => <button key={metric.label} className={`dc-kpi ${index === 0 ? 'dc-kpi-featured' : index === 1 ? 'dc-kpi-delivery' : index === 4 ? 'dc-kpi-attention' : ''}`} onClick={() => openOrders(metric.label, metric.explanation, metric.records)}><span className="dc-kpi-top">{metric.label}<span className="dc-kpi-icon"><metric.icon size={19} /></span></span><strong className="dc-kpi-value">{metric.value}</strong>{index === 1 && <span className="dc-delivery-track" aria-hidden="true"><span style={{ width: model.deliveryRate + '%' }} /></span>}<span className="dc-kpi-bottom">{metric.caption}<ArrowUpRight size={14} /></span></button>)}
      </div>
      <div className="dc-brief"><div className="dc-brief-icon"><Sparkles size={20} /></div><div><span className="dc-eyebrow">RINGKASAN ANDA</span><p>{filtered.length ? <><strong>{leader ? cityLabel(leader.id) : 'Wilayah ini'}</strong>{leader ? ` menyumbang ${Math.round(leader.value / (model.orderValue || 1) * 100)}% daripada nilai pesanan yang layak.` : ' mempunyai rekod untuk disemak.'} {model.attention.length > 0 ? `${model.attention.length} pesanan memerlukan perhatian operasi.` : 'Tiada pesanan tertunda atau diproses dalam paparan ini.'}</> : 'Tiada rekod dalam filter ini. Pilih tempoh atau wilayah lain untuk meneroka prestasi.'}</p></div><button onClick={() => openOrders('Keutamaan operasi', 'Pesanan tertunda dan diproses daripada filter aktif.', model.attention)} className="dc-text-button">Semak keutamaan <ArrowRight size={16} /></button></div>
      <div className="dc-main-grid">
        <Panel className="dc-regions"><div className="dc-panel-heading"><div><span className="dc-eyebrow">PRESTASI WILAYAH</span><h2>Di mana bisnes berkembang</h2><p>Nilai pesanan mengikut hab · MYR</p></div><button className="dc-icon-button" aria-label="Lihat rekod wilayah" onClick={() => openOrders('Rekod prestasi wilayah', 'Carta dan KPI menggunakan pesanan yang sama. Refund dan pesanan batal dikecualikan.', filtered.filter(order => !['Refunded', 'Cancelled'].includes(order.status)))}><ArrowUpRight size={18} /></button></div>
          {model.regions.length ? <div className="dc-chart"><ResponsiveContainer width="100%" height={Math.max(260, model.regions.length * 32)}><BarChart data={model.regions} layout="vertical" margin={{ left: 5, right: 32, top: 12, bottom: 4 }}><CartesianGrid stroke="var(--dc-border)" horizontal={false} strokeDasharray="3 5" /><XAxis type="number" tickFormatter={value => value >= 1000 ? `${value / 1000}k` : String(value)} axisLine={false} tickLine={false} tick={{ fill: 'var(--dc-muted)', fontSize: 11 }} /><YAxis dataKey="name" type="category" width={128} interval={0} axisLine={false} tickLine={false} tick={{ fill: 'var(--dc-muted)', fontSize: 11 }} /><Tooltip cursor={{ fill: 'var(--dc-soft)' }} contentStyle={{ background: 'var(--dc-surface)', border: '1px solid var(--dc-border)', borderRadius: 12, color: 'var(--dc-text)' }} formatter={(value) => [money(Number(value)), 'Nilai pesanan']} /><Bar dataKey="value" fill="var(--dc-chart-bar)" radius={[0, 6, 6, 0]} maxBarSize={23} isAnimationActive={false} /></BarChart></ResponsiveContainer></div> : <div className="dc-empty dc-chart-empty"><BarChart3 size={30} /><strong>Belum ada nilai pesanan</strong><span>Data akan muncul apabila ada rekod yang layak.</span></div>}
          <div className="dc-chart-footer"><span><Database size={13} /> Sumber: rekod pesanan tempatan</span><button className="dc-text-button" onClick={() => openOrders('Semua rekod wilayah', 'Semua pesanan daripada wilayah dan tempoh yang dipilih.')}>Teroka rekod <ArrowRight size={14} /></button></div>
        </Panel>
        <Panel className="dc-attention"><div className="dc-panel-heading"><div><span className="dc-eyebrow">KEUTAMAAN OPERASI</span><h2>Perlu perhatian</h2></div><span className="dc-count">{model.attention.length}</span></div><div className="dc-attention-list">{model.attention.slice(0, 3).map(order => <button className="dc-attention-item" key={order.order_id} onClick={() => openOrders(order.order_id, 'Semak rekod sebelum membuat keputusan operasi.', [order])}><span className={`dc-task-icon ${order.status === 'Delayed' ? 'dc-task-critical' : ''}`}>{order.status === 'Delayed' ? <Truck size={18} /> : <Package size={18} />}</span><span><strong>{order.status === 'Delayed' ? 'Penghantaran tertunda' : 'Pesanan sedang diproses'}</strong><small>{order.order_id} · {cityLabel(order.city)}</small><span className={`dc-status dc-status-${order.status}`}>{statusLabels[order.status]}</span></span><ChevronRight size={16} /></button>)}{!model.attention.length && <div className="dc-empty"><Check size={25} /><strong>Semua terkawal</strong><span>Tiada pesanan memerlukan perhatian dalam filter ini.</span></div>}</div><button className="dc-button dc-secondary dc-full" onClick={() => openOrders('Semua keutamaan', 'Pesanan tertunda diikuti pesanan diproses, mengikut filter aktif.', model.attention)}>Lihat semua keutamaan <ArrowRight size={15} /></button><div className="dc-quality-link"><ShieldCheck size={20} /><div><strong>Meja semakan kualiti</strong><span>Bukti dahulu, keputusan kemudian.</span></div><button className="dc-icon-button" aria-label="Buka semakan JEV" onClick={() => navigate('discovery')}><ArrowUpRight size={17} /></button></div></Panel>
      </div>
      <div className="dc-bottom-grid"><Panel><div className="dc-panel-heading"><div><span className="dc-eyebrow">FULFILLMENT</span><h2>Perjalanan pesanan</h2></div><Truck size={19} className="dc-muted" /></div><div className="dc-fulfillment"><div className="dc-donut">{model.statuses.length ? <ResponsiveContainer width="100%" height={170}><PieChart><Pie data={model.statuses} dataKey="value" nameKey="name" innerRadius={54} outerRadius={72} paddingAngle={3} stroke="none" isAnimationActive={false}>{model.statuses.map(item => <Cell key={item.status} fill={statusColors[item.status]} />)}</Pie><Tooltip contentStyle={{ background: 'var(--dc-surface)', border: '1px solid var(--dc-border)', borderRadius: 12, color: 'var(--dc-text)' }} /></PieChart></ResponsiveContainer> : null}<div className="dc-donut-label"><strong>{Math.round(model.deliveryRate)}%</strong><span>selesai</span></div></div><div className="dc-status-list">{model.statuses.map(item => <button key={item.status} onClick={() => openOrders(item.name, 'Pesanan mengikut status dalam filter aktif.', filtered.filter(order => order.status === item.status))}><span className="dc-legend-dot" style={{ background: statusColors[item.status] }} /><span>{item.name}</span><strong>{item.value}</strong><ChevronRight size={13} /></button>)}{!model.statuses.length && <span className="dc-muted">Tiada data status.</span>}</div></div></Panel><Panel className="dc-workspace-panel"><div className="dc-panel-heading"><div><span className="dc-eyebrow">RUANG KERJA</span><h2>Teruskan langkah seterusnya</h2><p>Semua fungsi penting, satu aliran kerja.</p></div></div><div className="dc-shortcuts">{[{ name: 'Pesanan', caption: 'Semak & urus rekod', tab: 'orders', icon: Package }, { name: 'Logistik', caption: 'Kargo bas & ejen', tab: 'bus_freight', icon: Truck }, { name: 'Laporan', caption: 'Analisis lebih mendalam', tab: 'reports', icon: FileText }, { name: 'Prestasi AI', caption: 'Pantau ejen operasi', tab: 'agent_performance', icon: Sparkles }].map(link => <button key={link.tab} onClick={() => navigate(link.tab)}><link.icon size={20} /><strong>{link.name}</strong><span>{link.caption}</span><ArrowUpRight size={14} /></button>)}</div></Panel></div>
      <Panel className="dc-orders"><div className="dc-panel-heading"><div><span className="dc-eyebrow">REKOD OPERASI</span><h2>Setiap pesanan, lebih jelas</h2></div><button className="dc-text-button" onClick={() => navigate('orders')}>Urus pesanan <ArrowRight size={15} /></button></div><div className="dc-table-toolbar"><div className="dc-tabs" role="group" aria-label="Paparan pesanan">{([{ id: 'all', label: 'Semua' }, { id: 'attention', label: 'Perlu perhatian' }, { id: 'delivered', label: 'Selesai' }] as const).map(tab => <button key={tab.id} aria-pressed={tableTab === tab.id} onClick={() => setTableTab(tab.id)}>{tab.label}</button>)}</div><label className="dc-search"><Search size={15} /><input aria-label="Cari pesanan" placeholder="Cari pesanan atau produk…" value={query} onChange={event => setQuery(event.target.value)} />{query && <button className="dc-clear-search" aria-label="Kosongkan carian pesanan" onClick={() => setQuery('')}><X size={14} /></button>}</label></div><OrderRows orders={tableOrders.slice(0, 6)} onSelect={order => openOrders(order.order_id, 'Maklumat pesanan daripada rekod tempatan.', [order])} /><div className="dc-chart-footer"><span>{Math.min(6, tableOrders.length)} daripada {tableOrders.length} pesanan</span>{tableOrders.length > 6 && <button className="dc-text-button" onClick={() => openOrders('Hasil carian pesanan', 'Semua rekod yang memenuhi filter dan carian.', tableOrders)}>Lihat semua <ArrowRight size={14} /></button>}</div></Panel>
      {dashboards.length > 0 && <details className="dc-artifacts"><summary><Sparkles size={16} /> Dashboard analitik tersimpan <span>{dashboards.length}</span></summary><div>{[...dashboards].reverse().map((dashboard, index) => <SavedArtifact key={`${dashboard.title}-${index}`} dashboard={dashboard} />)}</div></details>}
      <footer className="dc-footer"><span><Database size={12} /> Data awal contoh + rekod tempatan · belum disahkan dengan backend</span><span>{latestDate ? `Rekod terkini: ${new Date(latestDate).toLocaleDateString('ms-MY')}` : 'Belum ada rekod'}</span></footer>
    </div>
    <dialog ref={dialogRef} className="dc-dialog" onCancel={closeDetail} onClose={() => { setDetail(null); originRef.current?.focus(); }} onClick={event => { if (event.target === event.currentTarget) closeDetail(); }} aria-labelledby="dc-detail-title"><div className="dc-dialog-content"><header><div><span className="dc-eyebrow">BUTIRAN & SUMBER</span><h2 id="dc-detail-title">{detail?.title}</h2></div><button autoFocus className="dc-icon-button" aria-label="Tutup butiran" onClick={closeDetail}><X size={20} /></button></header><p>{detail?.description}</p><span className="dc-demo-label">REKOD TEMPATAN · {detail?.orders.length ?? 0} PESANAN</span><OrderRows orders={detail?.orders ?? []} /><div className="dc-dialog-actions"><button className="dc-button dc-secondary" onClick={closeDetail}>Kembali ke dashboard</button><button className="dc-button dc-primary" onClick={() => { closeDetail(); navigate('orders'); }}>Buka modul pesanan <ArrowRight size={15} /></button></div></div></dialog>
    <div className="dc-toast" role="status" aria-live="polite">{notice && <span><Check size={16} />{notice}</span>}</div>
  </div>;
}
