import type { FlowDefinition, FlowIntent, FlowNode, FlowSession } from '../../shared/platform-contracts';
import { Auth, type Principal } from './auth';
import { Commerce } from './commerce';
import { Dealers } from './dealers';
import { Work } from './work';
import { fields, fail, id, integer, list, now, object, oneOf, PlatformStore, text } from './store';

const TEMPLATE_FIELDS:Record<FlowIntent,{field:string;label:string}[]>={order:[{field:'lines',label:'Pilih produk dan kuantiti'},{field:'fulfilment',label:'Pickup atau penghantaran'},{field:'contactRef',label:'Maklumat penerimaan'}],complaint:[{field:'orderId',label:'Pilih pesanan sendiri'},{field:'subject',label:'Tajuk isu'},{field:'description',label:'Terangkan isu'}],dealer_application:[{field:'organization',label:'Nama organisasi'},{field:'description',label:'Rancangan perniagaan'}],restock:[{field:'quoteId',label:'Quotation restock yang disemak'}],stock_receipt:[{field:'shipmentId',label:'ID penghantaran'},{field:'lines',label:'Kuantiti yang diterima'},{field:'expectedRevision',label:'Versi penghantaran'}]};
const TITLES:Record<FlowIntent,string>={order:'Beli produk',complaint:'Laporkan isu pesanan',dealer_application:'Mohon dealer',restock:'Pesan restock',stock_receipt:'Terima stok dealer'};
const ALLOWED_FIELDS:Record<FlowIntent,string[]>={order:['lines','catalogueVersion','fulfilment','contactRef','outletId'],complaint:['orderId','subject','description'],dealer_application:['organization','description'],restock:['quoteId'],stock_receipt:['shipmentId','lines','expectedRevision']};
export class Flows {
  constructor(readonly store:PlatformStore,readonly auth:Auth,readonly commerce:Commerce,readonly work:Work,readonly dealers:Dealers){
    // Product-owned UI schemas are initialized; no product, order, policy, user or stock data is seeded.
    for(const intent of Object.keys(TEMPLATE_FIELDS) as FlowIntent[])if(!store.get('flows',`${intent}-v1`)){
      const prompts=TEMPLATE_FIELDS[intent];const nodes:FlowNode[]=prompts.map((prompt,index)=>({id:prompt.field,kind:prompt.field==='fulfilment'?'choice':'text',field:prompt.field,label:prompt.label,required:true,maxLength:6000,next:prompts[index+1]?.field??'review',...(prompt.field==='fulfilment'?{options:[{label:'Pickup',value:'pickup',next:'contactRef'},{label:'Penghantaran',value:'delivery',next:'contactRef'}]}:{})}));nodes.push({id:'review',kind:'review',label:'Semak sebelum hantar',next:'receipt'},{id:'receipt',kind:'receipt',label:'Resit submission'});store.save<FlowDefinition>('flows',{id:`${intent}-v1`,slug:intent.replaceAll('_','-'),title:TITLES[intent],version:1,entry:nodes[0].id,nodes,intent,audience:['customer','founder'],status:'published'});
    }
  }
  all(){const definitions=this.store.all<FlowDefinition>('flows').filter(d=>d.status==='published');return definitions.filter(d=>!definitions.some(other=>other.slug===d.slug&&other.version>d.version));}
  definition(slug:string){return this.all().find(d=>d.slug===slug||d.id===slug)??fail('NOT_FOUND',404);}
  save(actor:Principal,raw:unknown){this.auth.founder(actor);const input=object(raw);fields(input,['slug','title','entry','nodes','intent','audience','publish']);const slug=text(input.slug,'Slug',80);if(!/^[a-z0-9-]+$/.test(slug))fail('INVALID_SLUG');const intent=oneOf(input.intent,['order','complaint','dealer_application','restock','stock_receipt'] as const);const nodes:FlowNode[]=list(input.nodes,60).map(value=>{const n=object(value);fields(n,['id','kind','field','label','required','maxLength','next','options']);const kind=oneOf(n.kind,['choice','text','attachment','review','receipt'] as const);if(n.required!==undefined&&typeof n.required!=='boolean')fail('INVALID_FLOW');const field=n.field?text(n.field,'Field',80):undefined;if(field&&!ALLOWED_FIELDS[intent].includes(field))fail('INVALID_FLOW_FIELD');return {id:text(n.id,'Node',80),kind,...(field?{field}:{}),...(n.label?{label:text(n.label,'Label',200)}:{}),required:n.required===true,...(n.maxLength!==undefined?{maxLength:integer(n.maxLength,'Max length',1,10000)}:{}),...(n.next?{next:text(n.next)}:{}),...(n.options?{options:list(n.options,30).map(v=>{const option=object(v);fields(option,['label','value','next']);return {label:text(option.label,'Label',200),value:text(option.value,'Value',200),next:text(option.next,'Next',80)};})}:{})};});const ids=new Set(nodes.map(n=>n.id));if(ids.size!==nodes.length||!ids.has(text(input.entry))||!nodes.some(n=>n.kind==='review')||!nodes.some(n=>n.kind==='receipt')||nodes.some(n=>(n.next&&!ids.has(n.next))||n.options?.some(o=>!ids.has(o.next))))fail('INVALID_FLOW_GRAPH');const audience=list(input.audience,4).map(v=>oneOf(v,['customer','staff','founder','developer'] as const));if(!audience.length)fail('INVALID_FLOW_AUDIENCE');const version=Math.max(0,...this.store.all<FlowDefinition>('flows').filter(d=>d.slug===slug).map(d=>d.version))+1;const record:FlowDefinition={id:id(),slug,title:text(input.title,'Tajuk',200),entry:text(input.entry),nodes,intent,audience,version,status:input.publish===true?'published':'draft'};this.store.save('flows',record);this.store.audit(actor.user.id,'flow.publish',record.id,record.version);return record;}
  session(actor:Principal,sessionId:string){const session=this.store.require<FlowSession>('flow_sessions',sessionId);if(session.ownerId!==actor.user.id)fail('FORBIDDEN',403);if(session.expiresAt<=now()&&session.status==='draft')fail('FLOW_EXPIRED',409);return session;}
  form(actor:Principal,sessionId:string,raw:unknown){
    const input=object(raw);fields(input,['expectedRevision','answers']);
    const session=this.session(actor,sessionId);this.store.revision(session.revision,input.expectedRevision);
    if(session.status!=='draft')fail('FLOW_ALREADY_SUBMITTED',409);
    const definition=this.store.require<FlowDefinition>('flows',session.flowId),answers=object(input.answers);
    fields(answers,ALLOWED_FIELDS[definition.intent]);if(JSON.stringify(answers).length>32000)fail('ANSWERS_TOO_LARGE',413);
    // Both interfaces share the same pinned schema and canonical domain validation.
    for(const node of definition.nodes)if(node.field){const value=answers[node.field];if(node.required&&(value===undefined||value===''))fail('FLOW_FIELD_REQUIRED');if(typeof value==='string'&&value.length>(node.maxLength??6000))fail('FLOW_FIELD_INVALID');if(node.kind==='choice'&&!node.options?.some(option=>option.value===value))fail('FLOW_CHOICE_INVALID');}
    const draft={...session,answers};this.validate(actor,draft);
    const updated:FlowSession={...draft,currentNode:definition.nodes.find(node=>node.kind==='review')!.id,reviewVersion:this.commerce.version(),revision:session.revision+1,...(definition.intent==='order'?{reviewQuote:this.commerce.quote(actor,answers)}:{})};
    this.store.save('flow_sessions',updated);return updated;
  }
  start(actor:Principal,raw:unknown){const input=object(raw);fields(input,['flowId']);const definition=this.store.require<FlowDefinition>('flows',text(input.flowId));if(definition.status!=='published'||!actor.memberships.some(m=>definition.audience.includes(m.role)))fail('FLOW_ENTRY_DENIED',403);const session:FlowSession={id:id(),flowId:definition.id,version:definition.version,currentNode:definition.entry,revision:1,status:'draft',answers:{},ownerId:actor.user.id,expiresAt:new Date(Date.now()+7*24*3600_000).toISOString()};this.store.save('flow_sessions',session);return session;}
  advance(actor:Principal,sessionId:string,raw:unknown,back=false){const input=object(raw);fields(input,back?['expectedRevision']:['expectedRevision','answers']);const session=this.session(actor,sessionId);this.store.revision(session.revision,input.expectedRevision);if(session.status!=='draft')fail('FLOW_ALREADY_SUBMITTED',409);const definition=this.store.require<FlowDefinition>('flows',session.flowId),current=definition.nodes.find(n=>n.id===session.currentNode)!;let answers=session.answers,currentNode=session.currentNode;
    if(back){const index=definition.nodes.findIndex(n=>n.id===current.id);currentNode=definition.nodes[Math.max(0,index-1)].id;}
    else {const patch=object(input.answers);fields(patch,ALLOWED_FIELDS[definition.intent]);if(JSON.stringify(patch).length>32000)fail('ANSWERS_TOO_LARGE',413);answers={...answers,...patch};if(current.field&&current.required&&(answers[current.field]===undefined||answers[current.field]===''))fail('FLOW_FIELD_REQUIRED');if(current.field&&typeof answers[current.field]==='string'&&String(answers[current.field]).length>(current.maxLength??6000))fail('FLOW_FIELD_INVALID');if(current.kind==='choice'){const selected=current.options?.find(option=>option.value===answers[current.field!]);if(!selected)fail('FLOW_CHOICE_INVALID');currentNode=selected.next;}else currentNode=current.next??currentNode;}
    const updated:FlowSession={...session,answers,currentNode,revision:session.revision+1};delete updated.reviewVersion;delete updated.reviewQuote;this.store.save('flow_sessions',updated);return updated;}
  validate(actor:Principal,session:FlowSession){const definition=this.store.require<FlowDefinition>('flows',session.flowId);fields(session.answers,ALLOWED_FIELDS[definition.intent]);switch(definition.intent){case 'order':this.commerce.quote(actor,session.answers);oneOf(session.answers.fulfilment,['pickup','delivery'] as const);text(session.answers.contactRef);break;case 'complaint':this.commerce.order(actor,text(session.answers.orderId));text(session.answers.subject);text(session.answers.description);break;case 'dealer_application':text(session.answers.organization);text(session.answers.description);break;case 'restock':{const quote=this.store.require<{dealerOrgId:string;expiresAt:string}>('quotes',text(session.answers.quoteId));this.dealers.dealer(actor,quote.dealerOrgId);this.dealers.terms();if(quote.expiresAt<=now())fail('REQUOTE_REQUIRED',409);break;}case 'stock_receipt':{const restock=this.store.require<{dealerOrgId:string}>('restocks',text(session.answers.shipmentId));this.dealers.dealer(actor,restock.dealerOrgId);this.commerce.lines(session.answers.lines);integer(session.answers.expectedRevision);break;}}return definition;}
  review(actor:Principal,sessionId:string,raw:unknown){const input=object(raw);fields(input,['expectedRevision']);const session=this.session(actor,sessionId);this.store.revision(session.revision,input.expectedRevision);if(session.status!=='draft')fail('FLOW_ALREADY_SUBMITTED',409);this.validate(actor,session);const definition=this.store.require<FlowDefinition>('flows',session.flowId),updated={...session,currentNode:definition.nodes.find(n=>n.kind==='review')!.id,reviewVersion:this.commerce.version(),...(definition.intent==='order'?{reviewQuote:this.commerce.quote(actor,session.answers)}:{}),revision:session.revision+1};this.store.save('flow_sessions',updated);return updated;}
  submit(actor:Principal,sessionId:string,raw:unknown,key:unknown){this.session(actor,sessionId);return this.commerce.idem(actor,`flow.submit:${sessionId}`,key,raw,()=>{const input=object(raw);fields(input,['expectedRevision']);const session=this.session(actor,sessionId);this.store.revision(session.revision,input.expectedRevision);if(session.status!=='draft')fail('FLOW_ALREADY_SUBMITTED',409);if(session.reviewVersion===undefined)fail('REVIEW_REQUIRED',409);if(session.reviewVersion!==this.commerce.version()||session.reviewQuote&&session.reviewQuote.expiresAt<=now())fail('REQUOTE_REQUIRED',409);const definition=this.validate(actor,session);let result:{id:string};switch(definition.intent){case 'order':result=this.commerce.submitOrder(actor,session.answers,`${text(key)}:order`);break;case 'complaint':result=this.work.createCase(actor,session.answers);break;case 'dealer_application':result=this.dealers.apply(actor,session.answers);break;case 'restock':result=this.dealers.request(actor,session.answers,`${text(key)}:restock`);break;case 'stock_receipt':result=this.dealers.receive(actor,text(session.answers.shipmentId),{expectedRevision:session.answers.expectedRevision,lines:session.answers.lines},`${text(key)}:receive`);break;}const updated:FlowSession={...session,currentNode:definition.nodes.find(n=>n.kind==='receipt')!.id,status:'submitted',revision:session.revision+1,receipt:{entityId:result.id,submittedAt:now()}};this.store.save('flow_sessions',updated);this.store.audit(actor.user.id,'flow.submit',session.id,updated.revision);return updated;});}
}
