import type { CampaignRecord, CampaignAsset, ExportArtifact } from '../../shared/platform-contracts';
import { Auth, type Principal } from './auth';
import { Commerce } from './commerce';
import { Work } from './work';
import { fields, fail, id, integer, list, now, object, PlatformStore, strings, text, date } from './store';

export class Marketing {
  constructor(readonly store:PlatformStore,readonly auth:Auth,readonly commerce:Commerce,readonly work:Work){}
  get(actor:Principal,campaignId:string){this.work.staff(actor);const record=this.store.require<CampaignRecord>('campaigns',campaignId);if(record.ownerId!==actor.user.id)this.auth.founder(actor);return record;}
  all(actor:Principal){this.work.staff(actor);return this.store.all<CampaignRecord>('campaigns').filter(c=>c.ownerId===actor.user.id||this.auth.has(actor,'founder'));}
  save(actor:Principal,raw:unknown,campaignId?:string){this.work.staff(actor);const input=object(raw);fields(input,campaignId?['expectedRevision','title','objective','copy','assets','productIds','catalogueVersion','scheduledAt']:['title','objective','copy','assets','productIds','catalogueVersion','scheduledAt']);const existing=campaignId?this.get(actor,campaignId):null;if(existing)this.store.revision(existing.revision,input.expectedRevision);const assets:CampaignAsset[]=list(input.assets??[],50).map(rawAsset=>{const a=object(rawAsset);fields(a,['id','name','rights','consent','evidenceId']);const evidenceId=a.evidenceId?text(a.evidenceId):undefined;if(evidenceId){const evidence=this.store.require<{entityId:string;ownerId:string}>('evidence',evidenceId);this.work.entity(actor,evidence.entityId);}return {id:a.id?text(a.id):id(),name:text(a.name,'Nama aset',200),rights:text(a.rights,'Hak penggunaan',2000),consent:text(a.consent,'Consent',2000),...(evidenceId?{evidenceId}:{})};});const productIds=strings(input.productIds??[]);if(integer(input.catalogueVersion)!==this.commerce.version())fail('REQUOTE_REQUIRED',409);for(const productId of productIds)if(!this.commerce.catalogue().some(p=>p.id===productId))fail('PRODUCT_UNAVAILABLE',409);const record:CampaignRecord={id:existing?.id??id(),ownerId:existing?.ownerId??actor.user.id,title:text(input.title,'Tajuk',200),objective:text(input.objective,'Objektif',2000),copy:text(input.copy,'Caption',20000),assets,productIds,catalogueVersion:this.commerce.version(),status:'draft',revision:(existing?.revision??0)+1,createdAt:existing?.createdAt??now(),...(input.scheduledAt?{scheduledAt:date(input.scheduledAt)}:{})};if(existing)this.store.save('campaign_revisions',{...existing,id:`${existing.id}:${existing.revision}`,campaignId:existing.id});this.store.save('campaigns',record);this.store.audit(actor.user.id,'campaign.save',record.id,record.revision);return record;}
  approve(actor:Principal,campaignId:string,raw:unknown){this.auth.founder(actor);const input=object(raw);fields(input,['expectedRevision','approvalExpiresAt']);const record=this.get(actor,campaignId);this.store.revision(record.revision,input.expectedRevision);if(record.catalogueVersion!==this.commerce.version())fail('REQUOTE_REQUIRED',409);const approvalExpiresAt=date(input.approvalExpiresAt);if(approvalExpiresAt<=now()||Date.parse(approvalExpiresAt)>Date.now()+90*24*3600_000)fail('INVALID_EXPIRY');const updated={...record,status:record.scheduledAt?'planned' as const:'approved' as const,approvedBy:actor.user.id,approvalExpiresAt,revision:record.revision+1};this.store.save('campaigns',updated);this.store.audit(actor.user.id,'campaign.approve',campaignId,updated.revision);return updated;}
  export(actor:Principal,campaignId:string,raw:unknown,key:unknown){const record=this.get(actor,campaignId);return this.commerce.idem(actor,`campaign.export:${campaignId}`,key,raw,()=>{const input=object(raw);fields(input,['expectedRevision','format']);this.store.revision(record.revision,input.expectedRevision);if(!['approved','planned'].includes(record.status)||!record.approvalExpiresAt||record.approvalExpiresAt<=now())fail('APPROVAL_REQUIRED',409);if(record.catalogueVersion!==this.commerce.version())fail('APPROVAL_STALE',409);if(input.format!=='text'&&input.format!=='asset_bundle')fail('INVALID_EXPORT_FORMAT');const fileRefs=input.format==='asset_bundle'?record.assets.map(asset=>{if(!asset.evidenceId)fail('ASSET_FILE_REQUIRED',409);const evidence=this.store.require<{id:string;kind:string}>('evidence',asset.evidenceId);if(evidence.kind!=='file')fail('ASSET_FILE_REQUIRED',409);return evidence.id;}):[];const artifact:ExportArtifact={id:id(),campaignRevision:record.revision,format:input.format,fileRefs,status:'exported',content:record.copy};this.store.save('exports',{...artifact,campaignId});this.store.audit(actor.user.id,'campaign.export',campaignId,record.revision);return artifact;});}
}
