import type { BusinessSettings, DealerTerms, DayCloseRecord, ExpenseRecord, QcRecord, QcReading, ReconciliationRecord, ShiftRecord, StockLot, KnowledgeEntry, InventoryMovement } from '../../shared/platform-contracts';
import { Auth, type Principal } from './auth';
import { Commerce, type PaymentRecord } from './commerce';
import { Work } from './work';
import { fields, fail, id, integer, list, now, object, oneOf, PlatformStore, strings, text, date } from './store';

interface QcSop {id:string;knowledgeId:string;knowledgeVersion:number;version:number;readings:{name:string;unit:string;minimum:number;maximum:number}[];approvedBy:string}
const localDay=(stamp:string)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuala_Lumpur',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(stamp));
export class Operations {
  constructor(readonly store:PlatformStore,readonly auth:Auth,readonly commerce:Commerce,readonly work:Work){}
  cashPayments(outletId:string,day:string){return this.store.all<PaymentRecord>('payments').filter(payment=>payment.method==='cash'&&localDay(payment.createdAt)===day&&this.store.get<{outletId:string}>('orders',payment.orderId)?.outletId===outletId);}
  reviewDayClose(actor:Principal,recordId:string,raw:unknown){
    const input=object(raw);fields(input,['expectedRevision','countCashSen']);
    const record=this.store.require<DayCloseRecord>('dayclose',recordId);this.auth.operational(actor,record.outletId);this.store.revision(record.revision,input.expectedRevision);
    if(record.status!=='review')fail('INVALID_TRANSITION',409);
    const payments=this.cashPayments(record.outletId,record.date),expectedCashSen=payments.reduce((sum,payment)=>sum+(payment.state==='confirmed'?payment.amountSen:-payment.amountSen),0),countCashSen=integer(input.countCashSen,'Kiraan tunai',0,1_000_000_000);
    const updated={...record,expectedCashSen,countCashSen,paymentRefs:payments.map(payment=>payment.id),discrepancySen:countCashSen-expectedCashSen,revision:record.revision+1};
    this.store.save('dayclose',updated);this.store.audit(actor.user.id,'dayclose.refresh_review',recordId,updated.revision);return updated;
  }
  scoped<T extends {outletId:string;ownerId?:string}>(actor:Principal,kind:string):T[]{this.work.staff(actor);return this.store.all<T>(kind).filter(r=>this.auth.has(actor,'founder')||actor.memberships.some(m=>m.role==='staff'&&m.outletIds.includes(r.outletId)));}
  settings(){return this.store.get<BusinessSettings>('settings','business')??{id:'business',version:0,approvedPolicies:{},locale:'ms-MY' as const,timezone:'Asia/Kuala_Lumpur' as const};}
  saveSettings(actor:Principal,raw:unknown){this.auth.founder(actor);const input=object(raw);fields(input,['expectedVersion','paymentInstructions','contact','locations','dealerTerms']);const previous=this.settings();this.store.revision(previous.version,input.expectedVersion);const approvedPolicies={...previous.approvedPolicies};if(input.paymentInstructions!==undefined)approvedPolicies.paymentInstructions=text(input.paymentInstructions,'Arahan pembayaran',4000,0);if(input.contact!==undefined)approvedPolicies.contact=text(input.contact,'Contact',2000,0);if(input.locations!==undefined){approvedPolicies.locations=list(input.locations,100).map(value=>{const l=object(value);fields(l,['id','name','address','hours','verifiedAt']);return {id:text(l.id,'ID lokasi',120),name:text(l.name,'Lokasi',200),address:text(l.address,'Alamat',2000),hours:text(l.hours,'Waktu operasi',1000),verifiedAt:date(l.verifiedAt)};});for(const location of approvedPolicies.locations)this.store.save('locations',location);}
    if(input.dealerTerms!==undefined){const terms=object(input.dealerTerms);fields(terms,['minimumQuantity','packMultiple','priceBasisPoints','ownership','returnRules']);const policy:DealerTerms={version:(approvedPolicies.dealer?.version??0)+1,minimumQuantity:integer(terms.minimumQuantity,'Minimum',1,1_000_000),packMultiple:integer(terms.packMultiple,'Gandaan pek',1,10000),priceBasisPoints:integer(terms.priceBasisPoints,'Harga B2B basis points',1,10000),ownership:oneOf(terms.ownership,['owned','consigned'] as const),returnRules:text(terms.returnRules,'Terma pemulangan',6000),approvedAt:now()};approvedPolicies.dealer=policy;}
    const record:BusinessSettings={...previous,version:previous.version+1,approvedPolicies};this.store.save('settings',record);this.store.audit(actor.user.id,'settings.approve','business',record.version);return record;
  }
  expenses(actor:Principal){return this.scoped<ExpenseRecord>(actor,'expenses');}
  createExpense(actor:Principal,raw:unknown,key:unknown){
    const input=object(raw);fields(input,['outletId','amountSen','category','evidenceIds']);const outletId=text(input.outletId);this.auth.operational(actor,outletId);
    const evidenceIds=strings(input.evidenceIds??[]);for(const evidenceId of evidenceIds){const evidence=this.store.require<{entityId:string}>('evidence',evidenceId);this.work.entity(actor,evidence.entityId);}
    // Check current outlet/evidence access even when returning a cached receipt.
    return this.commerce.idem(actor,'expense.create',key,raw,()=>{const record:ExpenseRecord={id:id(),outletId,amountSen:integer(input.amountSen,'Amaun',1,1_000_000_000),category:text(input.category,'Kategori',200),evidenceIds,status:'draft',revision:1,ownerId:actor.user.id,createdAt:now()};this.store.save('expenses',record);this.store.audit(actor.user.id,'expense.create',record.id);return record;});
  }
  approveExpense(actor:Principal,expenseId:string,raw:unknown){this.auth.founder(actor);const input=object(raw);fields(input,['expectedRevision']);const record=this.store.require<ExpenseRecord>('expenses',expenseId);this.store.revision(record.revision,input.expectedRevision);if(record.status!=='draft')fail('INVALID_TRANSITION',409);if(!record.evidenceIds.length)fail('EVIDENCE_REQUIRED',409);const updated={...record,status:'approved' as const,revision:record.revision+1};this.store.save('expenses',updated);this.store.audit(actor.user.id,'expense.approve',expenseId,updated.revision);return updated;}
  reconciliationSources(paymentRefs:string[],expenseRefs:string[]) {
    return Object.fromEntries([...paymentRefs.map(ref=>['payments',ref]),...expenseRefs.map(ref=>['expenses',ref])].map(([kind,ref])=>[kind+':'+ref,new Bun.CryptoHasher('sha256').update(JSON.stringify(this.store.get(kind,ref)??null)).digest('hex')]));
  }
  reconcile(actor:Principal,raw:unknown){this.auth.founder(actor);const input=object(raw);fields(input,['period','paymentRefs','expenseRefs']);const paymentRefs=strings(input.paymentRefs??[]),expenseRefs=strings(input.expenseRefs??[]),discrepancies:string[]=[];for(const ref of paymentRefs){const p=this.store.get<PaymentRecord>('payments',ref);if(!p||p.state!=='confirmed')discrepancies.push(`PAYMENT_UNCONFIRMED:${ref}`);}for(const ref of expenseRefs){const e=this.store.get<ExpenseRecord>('expenses',ref);if(!e||e.status!=='approved')discrepancies.push(`EXPENSE_UNAPPROVED:${ref}`);}const record:ReconciliationRecord={id:id(),period:text(input.period,'Tempoh',100),paymentRefs,expenseRefs,sourceHashes:this.reconciliationSources(paymentRefs,expenseRefs),discrepancies,status:'review',revision:1};this.store.save('reconciliations',record);this.store.audit(actor.user.id,'reconciliation.review',record.id);return record;}
  approveReconciliation(actor:Principal,recordId:string,raw:unknown){this.auth.founder(actor);const input=object(raw);fields(input,['expectedRevision','reason']);const record=this.store.require<ReconciliationRecord>('reconciliations',recordId);this.store.revision(record.revision,input.expectedRevision);if(record.status!=='review')fail('INVALID_TRANSITION',409);if(!record.sourceHashes||JSON.stringify(record.sourceHashes)!==JSON.stringify(this.reconciliationSources(record.paymentRefs,record.expenseRefs)))fail('RECONCILIATION_SOURCE_CHANGED',409,'Rekod sumber berubah. Bina semakan reconciliation baharu.');if(record.discrepancies.length||record.paymentRefs.some(ref=>this.store.get<PaymentRecord>('payments',ref)?.state!=='confirmed')||record.expenseRefs.some(ref=>this.store.get<ExpenseRecord>('expenses',ref)?.status!=='approved'))fail('RECONCILIATION_DISCREPANCY',409,'Rujukan belum disahkan. Selesaikan rekod sumber dahulu.');const updated={...record,status:'approved' as const,revision:record.revision+1};this.store.save('reconciliations',updated);this.store.audit(actor.user.id,'reconciliation.approve',recordId,updated.revision);return updated;}
  createShift(actor:Principal,raw:unknown){const input=object(raw);fields(input,['outletId','staffIds','openingCount']);const outletId=text(input.outletId),staffIds=strings(input.staffIds);this.auth.operational(actor,outletId);if(!staffIds.length)fail('STAFF_REQUIRED');if(!this.auth.has(actor,'founder')&&!staffIds.includes(actor.user.id))fail('FORBIDDEN',403);for(const staffId of staffIds)if(!this.auth.memberships(staffId).some(m=>m.role==='founder'||(m.role==='staff'&&m.outletIds.includes(outletId))))fail('ASSIGNEE_SCOPE',409);if(this.store.all<ShiftRecord>('shifts').some(s=>s.outletId===outletId&&s.status!=='closed'))fail('SHIFT_ALREADY_OPEN',409);const record:ShiftRecord={id:id(),outletId,staffIds,status:'open',openedAt:now(),openingCount:integer(input.openingCount,'Kiraan awal',0),revision:1};this.store.save('shifts',record);this.store.audit(actor.user.id,'shift.open',record.id);return record;}
  handoff(actor:Principal,shiftId:string,raw:unknown){const input=object(raw);fields(input,['expectedRevision','closingCount','handoffNote']);const record=this.store.require<ShiftRecord>('shifts',shiftId);this.auth.operational(actor,record.outletId);this.store.revision(record.revision,input.expectedRevision);if(record.status!=='open'||(!this.auth.has(actor,'founder')&&!record.staffIds.includes(actor.user.id)))fail('INVALID_TRANSITION',409);const updated={...record,status:'handoff' as const,revision:record.revision+1,closingCount:integer(input.closingCount,'Kiraan akhir',0),handoffNote:text(input.handoffNote,'Nota serahan',6000)};this.store.save('shifts',updated);this.store.audit(actor.user.id,'shift.handoff',shiftId,updated.revision);return updated;}
  acknowledgeShift(actor:Principal,shiftId:string,raw:unknown){const input=object(raw);fields(input,['expectedRevision']);const record=this.store.require<ShiftRecord>('shifts',shiftId);this.auth.operational(actor,record.outletId);this.store.revision(record.revision,input.expectedRevision);if(record.status!=='handoff')fail('INVALID_TRANSITION',409);const updated={...record,status:'closed' as const,revision:record.revision+1,acknowledgedBy:actor.user.id,closedAt:now()};this.store.save('shifts',updated);this.store.audit(actor.user.id,'shift.acknowledge',shiftId,updated.revision);return updated;}
  createDayClose(actor:Principal,raw:unknown){const input=object(raw);fields(input,['outletId','date','countCashSen']);const outletId=text(input.outletId),day=text(input.date,'Tarikh',10);if(!/^\d{4}-\d{2}-\d{2}$/.test(day)||!Number.isFinite(Date.parse(day)))fail('INVALID_DATE');this.auth.operational(actor,outletId);if(this.store.all<DayCloseRecord>('dayclose').some(d=>d.outletId===outletId&&d.date===day))fail('DAY_ALREADY_RECORDED',409);const payments=this.store.all<PaymentRecord>('payments').filter(p=>p.method==='cash'&&localDay(p.createdAt)===day&&this.store.get<{outletId:string}>('orders',p.orderId)?.outletId===outletId),expectedCashSen=payments.reduce((sum,p)=>sum+(p.state==='confirmed'?p.amountSen:-p.amountSen),0),countCashSen=integer(input.countCashSen,'Kiraan tunai',0,1_000_000_000);const record:DayCloseRecord={id:id(),outletId,date:day,expectedCashSen,countCashSen,paymentRefs:payments.map(p=>p.id),discrepancySen:countCashSen-expectedCashSen,status:'review',revision:1};this.store.save('dayclose',record);this.store.audit(actor.user.id,'dayclose.review',record.id);return record;}
  approveDayClose(actor:Principal,recordId:string,raw:unknown){this.auth.founder(actor);const input=object(raw);fields(input,['expectedRevision','reason']);const record=this.store.require<DayCloseRecord>('dayclose',recordId);this.store.revision(record.revision,input.expectedRevision);if(record.status!=='review')fail('INVALID_TRANSITION',409);const currentPayments=this.cashPayments(record.outletId,record.date);const expected=currentPayments.reduce((sum,p)=>sum+(p.state==='confirmed'?p.amountSen:-p.amountSen),0);if(expected!==record.expectedCashSen||JSON.stringify(currentPayments.map(p=>p.id).sort())!==JSON.stringify([...record.paymentRefs].sort()))fail('DAY_CLOSE_SOURCE_CHANGED',409,'Rekod tunai berubah. Semak semula day close sebelum approval.');if(record.discrepancySen&&(!input.reason||typeof input.reason!=='string'||!input.reason.trim()))fail('DISCREPANCY_REASON_REQUIRED',409);const reason=input.reason?text(input.reason,'Sebab variance',4000):'No discrepancy';const updated={...record,status:'approved' as const,revision:record.revision+1,reason};this.store.save('dayclose',updated);this.store.audit(actor.user.id,'dayclose.approve',recordId,updated.revision);return updated;}
  saveQcSop(actor:Principal,raw:unknown){this.auth.founder(actor);const input=object(raw);fields(input,['knowledgeId','readings']);const knowledge=this.store.require<KnowledgeEntry>('knowledge',text(input.knowledgeId));if(knowledge.status!=='approved'||(knowledge.expiresAt&&knowledge.expiresAt<=now()))fail('SOP_NOT_APPROVED',409);const readings=list(input.readings,50).map(v=>{const r=object(v);fields(r,['name','unit','minimum','maximum']);if(typeof r.minimum!=='number'||typeof r.maximum!=='number'||!Number.isFinite(r.minimum)||!Number.isFinite(r.maximum)||r.minimum>r.maximum)fail('INVALID_QC_THRESHOLD');return {name:text(r.name,'Reading',120),unit:text(r.unit,'Unit',30),minimum:r.minimum,maximum:r.maximum};});if(!readings.length||new Set(readings.map(r=>r.name)).size!==readings.length)fail('INVALID_QC_THRESHOLD');const record:QcSop={id:id(),knowledgeId:knowledge.id,knowledgeVersion:knowledge.version,version:1,readings,approvedBy:actor.user.id};this.store.save('qc_sops',record);this.store.audit(actor.user.id,'qc.sop_approve',record.id);return record;}
  createQc(actor:Principal,raw:unknown){const input=object(raw);fields(input,['batchId','sopId','sopVersion','outletId','readings','evidenceIds']);const outletId=text(input.outletId);this.auth.operational(actor,outletId);const sop=this.store.require<QcSop>('qc_sops',text(input.sopId));if(integer(input.sopVersion)!==sop.version)fail('SOP_VERSION_STALE',409);const readings:QcReading[]=list(input.readings,50).map(value=>{const r=object(value);fields(r,['name','value','unit']);if(typeof r.value!=='number'||!Number.isFinite(r.value))fail('INVALID_QC_READING');return {name:text(r.name,'Reading',120),value:r.value,unit:text(r.unit,'Unit',30)};});if(new Set(readings.map(r=>r.name)).size!==readings.length)fail('DUPLICATE_QC_READING');if(readings.some(r=>!sop.readings.some(required=>r.name===required.name&&r.unit===required.unit)))fail('QC_READING_SCOPE');const record:QcRecord={id:id(),batchId:text(input.batchId),sopId:sop.id,sopVersion:sop.version,readings,operatorId:actor.user.id,outletId,status:'review',revision:1,evidenceIds:strings(input.evidenceIds??[])};for(const evidenceId of record.evidenceIds){const e=this.store.require<{entityId:string}>('evidence',evidenceId);this.work.entity(actor,e.entityId);const lot=this.store.get<StockLot>('lots',e.entityId);if(!lot||lot.batchId!==record.batchId||lot.locationId!==record.outletId)fail('QC_EVIDENCE_SCOPE',403);}this.store.save('qc',record);this.store.audit(actor.user.id,'qc.record',record.id);return record;}
  releaseQc(actor:Principal,recordId:string,raw:unknown){this.auth.founder(actor);const input=object(raw);fields(input,['expectedRevision']);const record=this.store.require<QcRecord>('qc',recordId);this.store.revision(record.revision,input.expectedRevision);if(record.status!=='review')fail('INVALID_TRANSITION',409);const sop=this.store.require<QcSop>('qc_sops',record.sopId),knowledge=this.store.require<KnowledgeEntry>('knowledge',sop.knowledgeId);if(knowledge.status!=='approved'||(knowledge.expiresAt&&knowledge.expiresAt<=now())||record.sopVersion!==sop.version)fail('SOP_NOT_APPROVED',409);if(!record.evidenceIds.length)fail('EVIDENCE_REQUIRED',409);if(record.readings.length!==sop.readings.length||new Set(record.readings.map(r=>r.name)).size!==record.readings.length||sop.readings.some(required=>!record.readings.some(r=>r.name===required.name&&r.unit===required.unit&&r.value>=required.minimum&&r.value<=required.maximum)))fail('QC_READING_FAILED',409);const lots=this.store.all<StockLot>('lots').filter(l=>l.batchId===record.batchId&&l.locationId===record.outletId&&l.status==='quarantine');if(!lots.length)fail('QUARANTINE_BATCH_NOT_FOUND',409);for(const lot of lots){this.store.save('lots',{...lot,status:'available' as const,revision:lot.revision+1});this.store.save<InventoryMovement>('movements',{id:id(),productId:lot.productId,ownerId:lot.ownerId,locationId:lot.locationId,quantityDelta:0,operationKey:`qc-release:${recordId}:${lot.id}`,sourceEntityId:recordId,createdAt:now()});}const updated={...record,status:'released' as const,revision:record.revision+1};this.store.save('qc',updated);this.store.audit(actor.user.id,'qc.release',recordId,updated.revision);return updated;}
}
